name: Ideas
description: Have a new idea for the development of community?
title: "[IDEA] <description here>"
labels: [enhancement]
assignees: vinzvinci
body:
  - type: input
    id: description
    attributes:
      label: Description of the idea
      placeholder: "What is your idea?"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the idea here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/web3community/support/blob/changes/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
